feat: add node power types and events
threefoldtech/tfchain_graphql pull request #90
Opened 2023-01-31 04:57 UTC by renauter

Related to:

- #88

2023-01-31 05:11 UTC, renauter commented
Tested on local node
Node 1 and Node  2 belong to Farm 1

![image](https://user-images.githubusercontent.com/73958772/215670814-de1aa5b7-0b9b-4e98-a42b-4bf5449dbdaa.png)

2023-01-31 09:37 UTC, DylanVerstraete requested changes
I think the nodepower should be part of the general node struct (just a json field) and not a seperate entity

2023-01-31 09:37 UTC, DylanVerstraete commented on src/mappings/power.ts
> +    let powerTargetChangedEvent = new TfgridModulePowerTargetChangedEvent(ctx).asV123
destructure fields for easier access:

```
let { nodeId, farmId, powerTarget } = new TfgridModulePowerTargetChangedEvent(ctx).asV123
```

2023-01-31 09:37 UTC, DylanVerstraete commented on src/mappings/power.ts
> +    let powerStateChangedEvent = new TfgridModulePowerStateChangedEvent(ctx).asV123
destructure fields for easier access:

```
let { nodeId, farmId, powerTarget } = new TfgridModulePowerTargetChangedEvent(ctx).asV123
```

2023-01-31 11:48 UTC, renauter commented
> I think the nodepower should be part of the general node struct (just a json field) and not a seperate entity

You mean in the `schema.graphql` file I guess?

2023-01-31 11:49 UTC, DylanVerstraete commented
> > I think the nodepower should be part of the general node struct (just a json field) and not a seperate entity
> 
> You mean in the `schema.graphql` file I guess?

Indeed

2023-01-31 13:20 UTC, DylanVerstraete commented
@renauter can you also rebase your changes because I just merged the firesquid branch

2023-02-02 08:06 UTC, DylanVerstraete commented
closing in favor of https://github.com/threefoldtech/tfchain_graphql/pull/92

2023-02-02 08:06 UTC, closed without merging